title: Herberson Blog
email: ab560mh8f@mozmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Este é o meu blog, aonde eu costumo publicar alguns conteudos, anotações,
  pensamentos, estudos e qualquer outra coisa que seja relevante.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hsmiranda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _hsmiranda
github_username:  hsmiranda

#theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
